/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_vthglyk_appmanager_SendPids.h"
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <fcntl.h>



#define SELECT_CPU      1
#define READY           2
#define S_READY         3
#define PASS_H_DIM      4


/*
 * Class:     com_vthglyk_appmanager_SendPids
 * Method:    send_Pids_to_kernel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vthglyk_appmanager_SendPids_send_1Pids_1to_1kernel
  (JNIEnv *env, jobject obj, jint H_table_dim, jintArray arr) {

    jint *H_table = (*env)->GetIntArrayElements(env, arr, 0);
    jint fd;

    fd = open("/dev/monitor",O_RDWR);

    if( fd == -1) {
        (*env)->NewStringUTF(env,"Monitor driver open error...\n");
    }
    else {
        sleep(1);

        ioctl(fd, PASS_H_DIM, &H_table_dim);

        write(fd, (long unsigned int *)H_table, sizeof(long unsigned int)*H_table_dim);

        sleep(1);
        close(fd);
        (*env)->NewStringUTF(env,"Everything went as planned\n");
    }
  }

