CC=${NDK_TOOLCHAIN}gcc
PRODUCT_OUT = /home/sem15f6/android-ndk-r10d/platforms/android-9/arch-arm/usr/lib

CFLAGS= --sysroot=${NDK_SYSROOT}
CFLAGS+= -I/home/sem15f6/android-ndk-r10d/platforms/android-9/arch-arm/usr/include 
LDFLAGS = -Wl -nostdlib #\
#	$(PRODUCT_OUT)/crtbegin_dynamic.o \
 #       $(PRODUCT_OUT)/crtend_android.o \
  #      -L/home/sem15f6/android-ndk-r10d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-ld -lm -lc -ldl



# Installation variables
EXEC_NAME = LTC

# Files needed for the build
OBJS 	= LTC.o chi_square_density.o ln_gamma_function.o gamma_function.o

# Make rules
all: LTC
.c.o:
	$(CC) $(CFLAGS) -c $<

LTC: ${OBJS}
	$(CC) -o $(EXEC_NAME) ${OBJS} $(LDFLAGS)  


clean:
	rm -f *.o $(EXEC_NAME) 
